CREATE TABLE IF NOT EXISTS bank_account
(
    ID                 UUID                   DEFAULT gen_random_uuid(),
    BANK_IFSC          VARCHAR(100)  NOT NULL,
    ACCOUNT_NUMBER     VARCHAR(100)  NOT NULL,
    ACCOUNT_NAME       VARCHAR(500)  NOT NULL,
    TRANSIT_NUMBER     VARCHAR(20)   NOT NULL,
    INSTITUTION_NUMBER VARCHAR(20)   NOT NULL,
    BALANCE            NUMERIC       NOT NULL DEFAULT '0.0',
    BANK_ACCOUNT_TYPE  VARCHAR(100)  NOT NULL,
    META_DATA          VARCHAR(5000),
    OVERDRAFT_BALANCE  NUMERIC       NOT NULL,
    INTEREST_RATE      NUMERIC       NOT NULL DEFAULT '0.0',
    IS_ACTIVE          BOOL          NOT NULL,

    CRE_TS             TIMESTAMPTZ   NOT NULL,
    LAST_UPD_TS        TIMESTAMPTZ   NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (BANK_IFSC) REFERENCES bank(ifsc)
);